### ISSUE TITLE
Inside a WHERE clause, the dropdown for the starting class must be disabled

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#10]
In must always be set to the same class as the end class of the "parent" criteria

**Comment by SteinerPascal** [comment]
Is that necessary? i thought i could be nice to have where childs as optionals? In any case, parent still decides for the children. For example: If the where child has the option notExists set and the parent gets set to optional then the where child also gets set to optional.

**Comment by SteinerPascal** [comment]
oh no that was clearly my mistake! I should have read the title more clearly (it was already late...). Will fix it!
