### ISSUE TITLE
Add SparnaturalVersion to JSON structure

### ISSUE THREAD

**Issue by SteinerPascal** [SteinerPascal/sparnatural-port#104]
@tfrancart I'm suggesting to add the sparnatural version to the JSON structure. This can be useful if somebody saves a query somewhere. Then updates sparnatural himself or sends it to someone with a different sparnatural version (which might contain changes incompatible with the saved JSON).

What do you think?

**Comment by tfrancart** [comment]
I think it won't hurt to add this, however:

1. The JSON queries are meant to be loaded and shared on the same Sparnatural instance
2. If a major Sparnatural update takes place, involving backward-incompatible changes to the JSON structure, then all the predefined queries can be updated at the same time as the update takes place.
3. The only case that won't work is if someone shares a link with the JSON query encoded inside, and Sparnatural cannot recognize it, but in this case if we have the Sparnatural version in the JSON, we will be able to load it only if the old parsing code has been kept.

So : yes, why not, but I think this will be of limited usage

**Comment by SteinerPascal** [comment]
agreed
