### ISSUE TITLE
On first variable selected, the width of sort area should be set equal to the width of first column selected

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#13]
![image](https://user-images.githubusercontent.com/2728945/172062890-6eb565dc-8e7f-42af-accb-c96edf68d4ac.png)

**Comment by SteinerPascal** [comment]
Do they need to align? That's a bit difficult since a user can change the variable name which might change the width of the element

**Comment by tfrancart** [comment]
Indeed, they always stay aligned:

![image](https://user-images.githubusercontent.com/2728945/172925208-c14bd621-25b7-4096-aeff-0754d8ad5b69.png)

![image](https://user-images.githubusercontent.com/2728945/172925267-a6cdeab0-ee85-41e3-872e-f5e04fbdd78c.png)

You can test at http://sparnatural.eu/demos/demo-dbpedia-v2/index.html?lang=en

**Comment by tfrancart** [comment]
Width is set on 3 events:

1. When focus is set on the first column name, when we edit the first column name (onFocusEdit())
2. When we have finished editing the first column name (onFocusOutEdit())
3. When the first element is removed (remove())
4. When there is a drag and drop (onEnd() on the Sortable object in initVariablesSelector())

**Comment by tfrancart** [comment]
OK, this works now **except** I can't find how to resize the sort option when the very first variable is added. Otherwise when edited or dragged or removed this works.

**Comment by SteinerPascal** [comment]
this seems to be a funny one. I've observed that when the calculation for the width is happening, the <i> tag icluding the fa-icon is not yet loaded. So the draggable is smaller and the function takes this width. and then the icon loads and makes the draggable bigger than the sortableoptions. So we have some async loading...

**Comment by SteinerPascal** [comment]
fixed with a listener (unfortunately will be triggered 3 times on each first load). alternative would be to have a placeholder till the icon is loaded. Since fa-icons are used on other places as well this could give styling bugs in other places as well.
Reference for solutions: https://blog.fontawesome.com/how-to-use-asynchronous-font-loading/
