### ISSUE TITLE
Move source to Sparnatural repository

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#136]
Now that the Typescript version is stable, why don't we move it to the Sparnatural repository ?
We would keep the Javascript version into an "archive" subdirectory or similar.
This would make it easier to keep both in synch during the continuation of a transition period, and I could prepare an "official beta version" of the typescript version.
What is your opinion on this transition @SteinerPascal ?

**Comment by SteinerPascal** [comment]
Yes I agree it's getting time to take over the typescript version. With two small detours. Let's first include the PR #134 and issue #137 and then we can move it? We can then bump Sparnatural to a new version (7.1 since all changes are backwards compatible right?)

**Comment by SteinerPascal** [comment]
Done, it's all ready. You can bring it home!

**Comment by SteinerPascal** [comment]
TODOs: on the Sparnatural git side:
- update Documentation: MapWidget, SERVICE keyowrd, integration into website
- update issues and branches: Delete all branches and issues which are not valid anymore.

**Comment by tfrancart** [comment]
@SteinerPascal : I moved the code from master into branch https://github.com/sparna-git/Sparnatural/tree/issue-298-TS-port of Sparnatural repository, and created an alpha release here : https://github.com/sparna-git/Sparnatural/releases/tag/8.0-alpha

I suggest we move any issues still open to the Sparnatural repository and continue work from here
