### ISSUE TITLE
Clean up Sparnatural

### ISSUE THREAD

**Issue by SteinerPascal** [SteinerPascal/sparnatural-port#137]
Some cleanups before we move the typescript version back to the old repository:

- move src/assets into static folder
- remove folder sparnatural-demo-dbpedia/ in favour of the static/default. Maybe change the name default to demo-dpedia
- move src/configs/fixed-configs to static folder
- remove yasgui.scss (I think this should be external?)
- remove the docker configs. If docker is needed provide it in a seperate repository

The last one aims at having a repository which can be used as an npm module. If somebody wants to have Sparnatural as a stand alone then it can be linked on the README to the docker version.

**Comment by SteinerPascal** [comment]
@tfrancart what do you think of the second and last points? Is this okay for you?

**Comment by tfrancart** [comment]
Yes, both are perfectly fine ! Thanks
