### ISSUE TITLE
Discuss the "tabs" evolution

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#16]
We don't have the use-cases for the "tabs" option.
The YASGUI integration is purely optional from Sparnatural point of view. Sparnatural should remain agnostic on the use or not of YASGUI.
If you need a tabbed feature, I suggest it is implemented outside of Sparnatural, in the webpage.

**Comment by SteinerPascal** [comment]
Okay fair enough! I will then disable the tabs in the yasgui.
