### ISSUE TITLE
What is the QueryExplainStringWriter?

### ISSUE THREAD

**Issue by SteinerPascal** [SteinerPascal/sparnatural-port#22]
@tfrancart 
Short question: what is the purpose of the queryexplainstringwriter?
https://github.com/SteinerPascal/sparnatural-port/blob/a2f339e21e9fc23eb68d670e36bc5e6a2223ca4a/src/sparnatural/sparql/Query.js#L969

**Comment by tfrancart** [comment]
This is unfinished. Do not worry about this.
The purpose was to produce a human-readable string representation of the query, mimicking the SPARQL query pattern, a string like:

```
Artwork located in Museum
where Museum country France
and Artwork author Picasso
```

**Comment by SteinerPascal** [comment]
Okay I understand. some kind of reverse NLP. Thanks!
