### ISSUE TITLE
port LiteralList Widget

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#35]
In Sparnatural there is a (not much used) LiteralListProperty
This is implemented with the ListWidget, the differences being that:

- values in the dropdrown do not have an IRI as value, but a Literal, the same as the option label of the dropdown
- the values inserted in the SPARQL query are literals, not IRIs

This is the case for "Person nationality Country" in the dev test page. The SPARQL query to populate the list is:

```
SELECT DISTINCT ?value (STR(?value) AS ?label)WHERE {    ?domain a <http://dbpedia.org/ontology/Person> .    ?domain <http://fr.dbpedia.org/property/nationalité> ?value .}ORDER BY UCASE(?label)LIMIT 500
```

It does return results. But the dropdown remains empty in Sparnatural.
Maybe this requires a separate widget.

**Comment by SteinerPascal** [comment]
Is this still open? I thought i saw this somewhere being fixed in a PR?

**Comment by tfrancart** [comment]
This is implemented in #112 , as a new widget, subclass of ListWidget

**Comment by SteinerPascal** [comment]
@tfrancart  further testing and if okay, then close it

**Comment by tfrancart** [comment]
Not OK, still pending, some of my modifications are missing in master branch

**Comment by tfrancart** [comment]
Fixed when ported the code to original repo
