### ISSUE TITLE
Left side of firt orange arrow should be straight and vertical, not shaped like the others

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#36]
Currently:

![image](https://user-images.githubusercontent.com/2728945/180015894-8ad997b7-8e86-4f2e-9492-1b04b52670d2.png)

Should be:

![image](https://user-images.githubusercontent.com/2728945/180015776-2a5c2801-e001-4312-8bbf-f205cfc6991e.png)

**Comment by antoine37120** [comment]
@tfrancart Fait !
Avec l'ajout d'une marge à gauche pour laisser le blanc tournant autour de l'élément

**Comment by tfrancart** [comment]
C'est OK, mais ca a du avoir des effets de bords (cf d'autres issues) - on en reparle
