### ISSUE TITLE
highlight orange arrows with green border when selected

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#37]
Currently

![image](https://user-images.githubusercontent.com/2728945/180016211-36a608dd-71d6-43a5-929b-5e89156d7deb.png)

Should be

![image](https://user-images.githubusercontent.com/2728945/180016094-888f9516-f7f0-4c88-9210-3a027f0a1fb6.png)

**Comment by antoine37120** [comment]
@tfrancart Fait mais une issue est à ajouter pour la prise en charge de la sélection de la start class.
