### ISSUE TITLE
[CSS] Port gradient of colors of the background

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#38]
Each line should get darker and darker.

Current:

![image](https://user-images.githubusercontent.com/2728945/180016575-984024e9-2347-4d32-9f74-3086d05f801d.png)

Should be:

![image](https://user-images.githubusercontent.com/2728945/180016731-c18554da-932a-4111-a0f9-a304d0975eab.png)

**Comment by antoine37120** [comment]
@tfrancart Celle-ci prendra un peu de temps

**Comment by tfrancart** [comment]
We need to port this piece of code which was triggered each time a component was added

```
		var $all_li = $(thisForm_.sparnatural).find('li.groupe') ;
		var leng = $all_li.length ;
		if (leng  <= 10 ) {
			leng = 10 ;
		}
		var ratio = 100 / leng / 100 ;
		var prev = 0 ;
		var cssdef = 'linear-gradient(180deg' ; 
		$all_li .each(function(index) {
			var a = (index + 1 ) * ratio ;
			var height = $(this).find('>div').outerHeight(true) ;
			cssdef += ', rgba('+settings.backgroundBaseColor+','+a+') '+prev+'px, rgba('+settings.backgroundBaseColor+','+a+') '+(prev+height)+'px' ;
			prev = prev + height+1 ;
			if ($(this).next().length > 0 ) {
				$(this).addClass('hasAnd') ;
				var this_li = $(this) ;
				
				var this_link_and = $(this).find('.link-and-bottom') ;
				
				$(this_link_and).height($(this_li).height() ) ;
			} else {
				 $(this).removeClass('hasAnd') ;
			}
		});

		$(thisForm_.sparnatural).find('div.bg-wrapper').css({background : cssdef+')' }) ;
```

**Comment by tfrancart** [comment]
@antoine37120 pourras-tu regarder car le code Javascript est bien là, le linear-gradient est bien mis, mais n'est pas pris en compte, il doit y avoir un problème de pure CSS :

![image](https://user-images.githubusercontent.com/2728945/180594728-e10bd4bc-c802-4a87-b10e-60e1a3f41f85.png)

La classe de l'élément a changé (builder-section à la place de bg-wrapper), ca a peut-être un lien ?

**Comment by tfrancart** [comment]
Now I understand : it works when you use an AND, but does not work when you use a WHERE. See:

![image](https://user-images.githubusercontent.com/2728945/180605360-b21cbf4f-73cd-4cbc-ad8b-69d84232124c.png)

this is because now the "groupe" are **nested** while before they were a flat list. So when we ask for the height of the first GroupWrapper we get the **total height** of the builder section, and the linear gradient gets false heights.

This is here : https://github.com/SteinerPascal/sparnatural-port/blob/84e11e00798e260a9053eb1fb64da9797204ae2b/src/sparnatural/statehandling/actions/InitGeneralEvent.ts#L21

**Comment by tfrancart** [comment]
Fixed now in branch css-fix in the PR

**Comment by antoine37120** [comment]
@tfrancart Fait sur issue-50 !
J'ai aussi déplacé une ligne dans Sparnatural.ts ici : https://github.com/sparna-git/sparnatural-port/blob/issue-50/src/sparnatural/components/Sparnatural.ts à cette ligne : https://github.com/sparna-git/sparnatural-port/blob/d27a319afed1d30310ec01a49ba4d0ab0792a063/src/sparnatural/components/Sparnatural.ts#L40

Le commit est ici : https://github.com/sparna-git/sparnatural-port/commit/d27a319afed1d30310ec01a49ba4d0ab0792a063#diff-0d59f4974aa3647f81fefa139fa5a64cd65bfefa46aa81b5d1c38973ec72da86

Ceci permet de lancer initGeneralEvent dès le lancement.
Le fait d'avoir déplacé cette ligne permet d'écouter plus tôt les events dans sparnatural.
Le code qui suit peut en déclencher.
