### ISSUE TITLE
Right-align of criteria lines

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#39]
Each criteria line should be right aligned - except the first one due to the cancel button

Current:

![image](https://user-images.githubusercontent.com/2728945/180017147-310e6249-c461-4f9a-a49d-41c6b7447bbd.png)

Should be

![image](https://user-images.githubusercontent.com/2728945/180016961-f2a6f988-f7a7-4627-87b4-40babb2aec9e.png)

**Comment by antoine37120** [comment]
@tfrancart Fait !
Mais il reste un petit soucis parce que le fond vert n'apparait pas dès le début
