### ISSUE TITLE
[CSS] Looks like positioning of 1 and 2 is not the same

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#43]
![image](https://user-images.githubusercontent.com/2728945/180593110-bdd1135a-2ba8-4fdb-ae56-ce3cef143a8a.png)

It looks like the cricle of the 2 is slightly to the left of the circle of the 1

**Comment by antoine37120** [comment]
@tfrancart Fait !
En remplaçant le symbole "+"  du bouton actionWhere par un icon fontawesome pour simplifier sont alignement vertical.
