### ISSUE TITLE
[CSS ?] StartClassGroup when under a Where must be disabled

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#45]
This should not be possible, the value must be fixed:

![image](https://user-images.githubusercontent.com/2728945/180593469-2a770d52-b363-4e6c-ad3b-6f77a5bf62d7.png)

**Comment by antoine37120** [comment]
@tfrancart On rediscutera de cette issue. Quelque chose dans le fonctionnement du rendu de cette liste me semble particulier.

**Comment by antoine37120** [comment]
@tfrancart Fait !
