### ISSUE TITLE
[CSS] Orange line of WHERE should not overlay bottom shadow of criteria group

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#46]
![image](https://user-images.githubusercontent.com/2728945/180593502-b8b10d34-b4d5-4016-8711-c7db43a54029.png)

should be

![image](https://user-images.githubusercontent.com/2728945/180593516-ac7cee8e-4298-4895-a9a7-a65bcefdf1dd.png)

**Comment by antoine37120** [comment]
@tfrancart Fait !
Corrige aussi le trait qui arrivait par dessus le startClass en dessous.

**Comment by tfrancart** [comment]
@antoine37120 2 remarques : 

1. Peux-tu appliquer le même traitement à la ligne du AND ?

![image](https://user-images.githubusercontent.com/2728945/181229218-96232e75-3724-412a-b0c3-cfe44f470a5c.png)

2. Peux-tu appliquer le même traitement à la ligne des sélecteurs "1" "2" qui est un peu plus basse :

![image](https://user-images.githubusercontent.com/2728945/181229403-4cddea75-c355-461b-b93a-6419daa870aa.png)

**Comment by tfrancart** [comment]
@antoine37120 je pense qu'il y a un souci de z-index, la ligne devient verte quand on descend dans la query, comme si elle passait derrière le background:

![image](https://user-images.githubusercontent.com/2728945/181232983-f0138295-c627-411a-9593-d8e12ae815c5.png)

Note : j'ai mergé issue-50 sur css-fix-2

**Comment by antoine37120** [comment]
@thomas Fait !
En ajoutant les corrections pour le z-index des autres traits ou en ajoutant une ombre par dessus le trait si impossible à gérer avec z-index.
