### ISSUE TITLE
[CSS] Align reset and play button

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#49]
![image](https://user-images.githubusercontent.com/2728945/180593795-06fb7f5d-ca3e-431e-a233-8bf4fc25dfb1.png)

**Comment by antoine37120** [comment]
@tfrancart Fait !
Inclut un fix pour les dimentions réduites du composant.
Chaque partie s'adapte en fonction de la taille du conteneur pricipal. 
Le choix est laissé pour ceux qui intégre le composant dans leur page de rendre ce conteneur avec une largeur minimale.
Le bloc de sélection des variables et maintenant aussi aligné avec une marge identique sur les côtés à celle des critères.
Voir ci-dessous :  
![image](https://user-images.githubusercontent.com/464395/181012165-63fe2894-b86a-4d12-a506-4f57404a8499.png)
