### ISSUE TITLE
Where lines screwed up when doing deep in query

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#51]
I go 4 level deep, then select "Any" value, and then the Where arrows are screwed up:

![image](https://user-images.githubusercontent.com/2728945/180594847-a995754d-13b8-4749-a14c-298bfeed6aad.png)

**Comment by tfrancart** [comment]
Apparently the fix of #50 in PR #56 also fixed this one (but I don't know why !)

**Comment by tfrancart** [comment]
Problem is still here.
How to reproduce:

1. Add 4 or 5 AND criterias
2. scroll to the top
3. Add a WHERE child under the first criteria and remove ti
4. scroll down a little
5. Add a WHERE child under the first criteria and remove it : BOOOOOM ! all WHERE and AND lines screwed up.

This is because of getBoundingClientRect() in LinkAndBottom and LinkWhereBottom

**Comment by SteinerPascal** [comment]
I haven't looked into it but it sounds like it comes from the scrolling part. Maybe there is some calculating for the lines based on absolut screen location? I can have a look at that if you like?

**Comment by tfrancart** [comment]
@SteinerPascal yes this comes from scrolling, can you have a look into it ? @antoine37120 told me this comes from `getBoundingClientRect` function, which works based on the **visible** part of the screen; another function should be used to get an absolute position.

**Comment by SteinerPascal** [comment]
Oke i will fix it cause using the absolute points for drawing the lines is ugly anyway. 
But should we think about having a max limit for where childs? And do we want to allow such big queries where it becomes scrollable?

**Comment by SteinerPascal** [comment]
this should do the trick. but it is based on window.ScrollY which is only available in firefox version 55 (released around 2017) and appearently there is a bug when doing pinch-zooming. That bug got resolved in later versions (both chrome and firefox)

**Comment by tfrancart** [comment]
> But should we think about having a max limit for where childs?

This is what the maxDepth config parameters does (should do)

**Comment by SteinerPascal** [comment]
Okay, well it works for the AND connections but not really for the WHERE. What is the idea here?
given: maxdepth = 5

Does that mean there are max 5 AND connections and each of them can have 5 Where connections?
Or 5 Connections in total? like 3 AND conn. and then 2 WHERE conn. ?

**Comment by tfrancart** [comment]
I fixed the maxDepth behavior in a PR, see https://github.com/SteinerPascal/sparnatural-port/issues/58
maxDepth controls the number of WHERE only.
Number of ANDs is unlimited, but we limit the number of WHERE otherwise we can run in display problems as the width becomes smaller and smaller each time we indent.
