### ISSUE TITLE
Missing an <ul> for nested lists (when doing a WHERE) ?

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#54]
Don't we miss an ul for the nested list when doing a WHERE ? we can't nest li directly inside li, we should have an intermediate ul class="componentList" I guess:

![image](https://user-images.githubusercontent.com/2728945/180605599-1088f1c7-feda-4713-bffd-0a91ea547d79.png)

**Comment by tfrancart** [comment]
Quick fix : wrap whereChild inside a `<ul>` - don't refactor too much

**Comment by SteinerPascal** [comment]
@tfrancart: I hope this is okay for you?
