### ISSUE TITLE
AND line and WHERE line are not aligned

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#60]
![image](https://user-images.githubusercontent.com/2728945/181231250-41e34998-0504-497b-bcde-2316d796d492.png)

the AND line should be at the same position as the WHERE line

@antoine37120 Tu as encore du temps pour regarder ça ?

**Comment by antoine37120** [comment]
@tfrancart On va plutôt aligner le Where au And. Nous avons besoin de place si il y a un enfant entre 2 frères

**Comment by tfrancart** [comment]
Oui très bien

**Comment by antoine37120** [comment]
@tfrancart C'est fait !
Au lieu de caller les liens à partir d'une valeur calculé de la largeur des StartClass il me semble plus sécur de partir d'une valeur fixe qui permet de rester à priori centré sur les icons si il y en a.
Dans les cas d'un critère nouvellement inséré le calcule ne marche pas parce que la largeur de StartClass n'est pas définitive quand ce calcule est réalisé. Et je ne vois pas le code qui pourrait s'exécuter après ce calcul.

**Comment by antoine37120** [comment]
@tfrancart avec un dernier fix pour n'avoir de bordure à gauche que pour le nice select dans StartClass.
