### ISSUE TITLE
eye in StartClassGroup has disappeared

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#62]
![image](https://user-images.githubusercontent.com/2728945/181904072-413e46d3-7be7-4e99-bdd8-349eeae38e22.png)

@antoine37120 can you have a look ?

**Comment by SteinerPascal** [comment]
I actually did that intentionally since the first class a user selects should always be visible?

**Comment by tfrancart** [comment]
> I actually did that intentionally since the first class a user selects should always be visible?

No, not necessarily. The rule is that there must be at least one selected variable; but it is possible to select another variable than the first one, and then unselect the first one.
It must not be possible to unselect a variable if it is the only one selected/

**Comment by SteinerPascal** [comment]
should be fine now
