### ISSUE TITLE
Selecting an OPTIONAL or NOT EXISTS when not in first line triggers an error in query generation

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#65]
`onQueryUpdated` should be called with the new query

**Comment by tfrancart** [comment]
Looks like it works when the optional / not exists is used on the first line, but not on an inner line.

`Museum > OPTIONAL country > Country` : works
```
Country > country of > Museum
WHERE
Museum > OPTIONAL country > Country
```

does not work, the query is not properly updated, because there is a bug in the SPARQL query generation:

![image](https://user-images.githubusercontent.com/2728945/182870613-df5bc6de-7a7d-423a-b69d-5a7de3602877.png)

**Comment by SteinerPascal** [comment]
Okee that bug got caused by a wrong index referencing of an array. I will make this more robust

**Comment by SteinerPascal** [comment]
should be okay now
