### ISSUE TITLE
deleting a criteria should update the SPARQL query

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#72]
onQueryUpdated should be called

**Comment by tfrancart** [comment]
Apparently in removeGrpWrapper the event generateQuery is properly sent, but never received in the ActionStore

**Comment by tfrancart** [comment]
@SteinerPascal maybe you can have a look at this one too ? a CustomEvent generateQuery is fired but never catched. What could be the reason ? We can also talk about it next time we talk. Thanks

**Comment by SteinerPascal** [comment]
Yes that happens since the grp wrapper is first deleted and then we try to send an event from it. but obviusly it's not there anymore. I will fix it.
