### ISSUE TITLE
Implement defaultLabelProperty

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#76]
As documented in https://docs.sparnatural.eu/OWL-based-configuration#classes-configuration-reference
Current code is at https://github.com/sparna-git/Sparnatural/blob/master/src/Query.js#L264

**Comment by tfrancart** [comment]
`defaultLabelProperty` annotation in the configuration indicates that when this class is selected as a column - with variable ?xxx_1 -, then another column is automatically added - with variable ?xxx_1_label, and populated with the property indicated by the annotation.
This really acts as if the user had added a criteria in its query, with the property indicated, "Any" value, and then click on the eye.
This is now done as a pre-processing on the JSON data structure to add the corresponding criteria automatically (https://github.com/sparna-git/Sparnatural/blob/master/src/Query.js#L264), before the JSON is turned into SPARQL.

@SteinerPascal how would you recommend to implement this in the new architecture where the SPARQL query is not generated from the JSON anymore ?

**Comment by SteinerPascal** [comment]
Hugh! that's a challenging one I have to admit. I have an idea but it's not really nice since it either kind of breaks the recursive cycle of processGrpWrapper() or I take the pre-processing you had and convert it in a post-processing. Let me work something out

**Comment by SteinerPascal** [comment]
Question: Is the default label only for classes defined in the config or also for <iri> values coming from widgets?

**Comment by tfrancart** [comment]
The defaultLabelProperty is an annotation associated to a **class** in the config. That class can be selected either in a startClassGroup or an endClassGroup.

**Comment by SteinerPascal** [comment]
I filed a PR. should be working now. I explained how it works in the PR.
