### ISSUE TITLE
TimeYearWidget automatically inserts an end value

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#77]
`Person > death date > Date`, then enter 2017 as the start year, and nothing in end year. The value inserted is "01/01/2017 - 31/12/2022". The expected value is "From 01/01/2017", with no end date

**Comment by SteinerPascal** [comment]
Is this also fixed in #84 ?

**Comment by tfrancart** [comment]
Yes, we can close
