### ISSUE TITLE
Confusion between n3.DataFactory and rdfjs.DataFactory - do not use N3.DataFactory

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#82]
sparqljs relies on RDFJS for type definitions.
However the code uses the DataFactory from n3 to build the terms.
This DataFactory does not return objects of the correct structure. The structure must be obtained by calling the toJSON() function on these objects (see https://rdf.js.org/N3.js/docs/N3DataFactory.html).

n3 DataFactory must not be used. Replace:

```
import { DataFactory } from "n3";
```

with

```
import * as DataFactory from "@rdfjs/data-model" ;
```

and all imports from ne should be replaced by imports from `@rdfjs/types` e.g. : 

```
import { Literal, NamedNode, Variable } from "@rdfjs/types";
```

**Comment by SteinerPascal** [comment]
Didn't know that N3 produces a different structure. Nice catch!
