### ISSUE TITLE
Fix WHERE CSS positioning

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#9]
![image](https://user-images.githubusercontent.com/2728945/172062586-835a7377-b33d-4724-9f8e-c7d0e9f27d64.png)

**Comment by SteinerPascal** [comment]
Can you elaborate on that? what's the issue?

**Comment by tfrancart** [comment]
Should look like this, centered around the line that goes down:

![image](https://user-images.githubusercontent.com/2728945/172925477-1b130d8f-0872-4e52-8b26-e2090561ecb0.png)
