### ISSUE TITLE
SPARQL query is wrong when combining defaultLabelProperty + OPTIONAL

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#93]
1. the predicate between startclass and endclass is missing
2. the optional part should be whatever is inside this criteria group, but not the defaultLabelProperty. 

![image](https://user-images.githubusercontent.com/2728945/186949214-48114792-4f5b-4779-905f-f028c6a6b53b.png)

**Comment by SteinerPascal** [comment]
I have fixed the first part. But is the 2nd part not contradictive with #94 ?

**Comment by SteinerPascal** [comment]
I'm reopening this. I have only fixed the 1. part of this issue.

**Comment by tfrancart** [comment]
Current Sparnatural code:

```
// set it optional if declared
newBranch.optional = this.specProvider.isEnablingOptional(labelProperty);
```
